spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
#    Comandos ddl geralmente não são usados em produção! Existe uma preferência pelo uso de script SQL.
    hibernate:
      ddl-auto: update
